name: CI

on:
  push:
    branches:
      main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: chipsalliance/verible-linter-action@v2.0
      with:
        config_file: '.veriblelint'
        paths: |
          ./src
        github_token: ${{ secrets.GH_TOKEN }}
